### ISSUE TITLE
Workshop Content link in README is broken

### ISSUE THREAD

**Issue by indcoder** [GlobalAICommunity/bootcamp-2022#1]
Clicking on the workshop content link

<img width="636" alt="image" src="https://user-images.githubusercontent.com/2099300/148404795-dca8c1e8-9b3a-4ef7-9ff4-bf60398d0e7b.png">

GitHub displays 404
<img width="882" alt="image" src="https://user-images.githubusercontent.com/2099300/148404590-72cb031b-f3f2-4ea3-8b23-c2b1f0e93965.png">

**Comment by indcoder** [comment]
Thank you, @SjoukjeZaal for correcting the existing workshops links and adding a new workshop via 582cb3dc0896500426d12d259d7c8098bcf17a93 

If there is no more additions to make for the workshop content in the README, you can close this issue.

**Comment by SjoukjeZaal** [comment]
Thanks for letting me know!
